# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- task: DotNetCoreCLI@2
  displayName: Publish Migrations
  inputs:
    command: publish
    publishWebProjects: false
    projects: src/DataModel.Migrations/DataModel.Migrations.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  displayName: Publish Task API
  inputs:
    command: publish
    publishWebProjects: false
    projects: src/TaskApi/TaskApi.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
    
- script: npm install
  displayName: 'Install npm packages'
  workingDirectory: 'src/Web.UI'
  
- script: npm run build
  displayName: 'Build Web.UI'
  workingDirectory: 'src/Web.UI'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'


