# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish Task API
  inputs:
    command: publish
    publishWebProjects: false
    projects: src/TaskApi/TaskApi.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: src/Web.UI
    verbose: false
    
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    workingDir: src/Web.UI
    verbose: false
    customCommand: 'run-script build'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Web Artifacts'
  inputs:
    PathtoPublish: src/Web.UI/dist
    ArtifactName: Web.UI



